# Generated by Django 5.0.2 on 2024-04-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20)),
                ('long_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('observations', models.TextField(max_length=1000)),
                ('duration', models.TextField(max_length=30)),
                ('persons_needed_min', models.IntegerField()),
                ('persons_needed_max', models.IntegerField()),
                ('phase', models.CharField(choices=[('before', 'Antes'), ('during', 'Durante'), ('after', 'Depois')], default='during', max_length=10)),
                ('departments_needed', models.ManyToManyField(to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('comission', 'Comissão'), ('volunteer', 'Voluntário')], max_length=20)),
                ('admin', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour_start', models.TimeField()),
                ('hour_end', models.TimeField()),
                ('backup', models.BooleanField(default=False)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.function')),
                ('members', models.ManyToManyField(to='api.member')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.space')),
            ],
        ),
    ]
