# Generated by Django 5.0.2 on 2024-04-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_department_long_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='function',
            old_name='persons_needed_max',
            new_name='members_needed_max',
        ),
        migrations.RenameField(
            model_name='function',
            old_name='persons_needed_min',
            new_name='members_needed_min',
        ),
        migrations.RemoveField(
            model_name='function',
            name='departments_needed',
        ),
        migrations.RemoveField(
            model_name='function',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
        migrations.AddField(
            model_name='function',
            name='vols_needed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.building'),
            preserve_default=False,
        ),
    ]
