# Generated by Django 5.0.2 on 2024-04-07 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_task_backup_remove_task_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='activities',
        ),
        migrations.CreateModel(
            name='ActivityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participant')),
            ],
        ),
    ]
