# Generated by Django 5.0.2 on 2024-04-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_participant_activities_activityparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='function',
            name='observations',
            field=models.TextField(),
        ),
    ]
