# Generated by Django 5.0.2 on 2024-04-09 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_resource_resourceassignment_team_function_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
