# Generated by Django 5.0.2 on 2024-04-09 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_function_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='duration',
        ),
    ]
