# Generated by Django 5.0.2 on 2024-04-09 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_function_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.member'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
    ]
